### ISSUE TITLE
How to extend list

### ISSUE THREAD

**Issue by altf4arnold** [unixorn/internet-of-trash#6]
Hey. 

I suppose that this list might become very long really fast. Any idea how we might make it easy to extend?

**Comment by unixorn** [comment]
For the time being, adding a line to the markdown table should be good enough. Markdown lets us use the GitHub native renderer and use them to serve the pages.

If this gets momentum and there are a lot of additions, I'll consider writing a github action to render the table from a yaml file or files.

**Comment by unixorn** [comment]
We can reopen this in the future if contribution volume becomes an issue.
